### PR TITLE
ov5693: Fix style issues

### PR DESCRIPTION
**Pull request by fabwu**
Fixes several checkstyle errors and warnings. There is no functional change.

### CODE REVIEW

**Comment by qzed** [comment]
Thanks! This is a good step forward to getting that driver cleaned up. I think formatting can (and before upstream submission probably should) still be improved, e.g. stuff like
```c
#define vcm_step_s(a) ((u8)((a) & 0xf))
#define vcm_step_mclk(a) ((u8)(((a) >> 4) & 0x3))
#define vcm_dlc_mclk(dlc, mclk) ((u16)(((dlc) << 3) | (mclk) | 0xa104))
#define vcm_tsrc(tsrc) ((u16)((tsrc) << 3 | 0xf200))
#define vcm_val(data, s) ((u16)((data) << 4 | (s)))
#define DIRECT_VCM vcm_dlc_mclk(0, 0)
```

to something like

```c
#define vcm_step_s(a)           ((u8)((a) & 0xf))
#define vcm_step_mclk(a)        ((u8)(((a) >> 4) & 0x3))
#define vcm_dlc_mclk(dlc, mclk) ((u16)(((dlc) << 3) | (mclk) | 0xa104))
#define vcm_tsrc(tsrc)          ((u16)((tsrc) << 3 | 0xf200))
#define vcm_val(data, s)        ((u16)((data) << 4 | (s)))
#define DIRECT_VCM              vcm_dlc_mclk(0, 0)

```

as well as consistent indentation (tabs, spaces, how many, ...) and documentation (`/*` vs `//`, capitalization, spaces) for those macros. There's also stuff that's commented out or ifdef-ed out, but all that's probably better taken care of when the IPU stuff is done, I think.

**Comment by qzed** [comment]
I've now also pushed an `ipu3-cameras` branch for all cameras stuff, so that we can keep better track of those changes. I think I can give you all access to that if you want to.

CC @djrscally, @kitakar5525

**Comment by djrscally** [comment]
Sure go for it; The cio2-bridge code is getting at least one more round of mostly-cosmetic tweaks upstream at the moment, but I can update it here too to keep everything in line.

**Comment by qzed** [comment]
@djrscally You should have access to it.

**Comment by fabwu** [comment]
Thanks for merging.

> There's also stuff that's commented out or ifdef-ed out, but all that's probably better taken care of when the IPU stuff is done, I think.

I'll first try to get the rotation fixed in the driver and libcamera. Then I plan to make the driver libcamera compatible (see [this patch](https://lists.libcamera.org/pipermail/libcamera-devel/2020-December/016128.html)) and remove the commented out sections.

**Pull request merged**
