### PR TITLE
Backporting 5.3/5.4 changes into 4.19

### PR DESCRIPTION
**Pull request by kitakar5525**
See also https://github.com/linux-surface/kernel/issues/31
This one large PR is composed of the following backports:
- old-patches-cleanup
- bugfix/touch-rotation (original PR: https://github.com/linux-surface/kernel/pull/3)
- feature/no-ipts-config-file (original PR: https://github.com/linux-surface/kernel/pull/11)
- feature/ipts-cleanup (original PR: https://github.com/linux-surface/kernel/pull/15)
- feature/companion-no-feedback (original PR: https://github.com/linux-surface/kernel/pull/16)
- wifi-suspend-fix
- feature/ipts-no-modeswitch (original PR: https://github.com/linux-surface/kernel/pull/23)

I first wanted to separate this one large PR into multiple PRs, but one logical change depends on another change. So, sending one large PR.
- ~[ ]~ Is this OK?
- ~[ ]~ Is there another better way?

Commit that needs discussion:
- [x] https://github.com/linux-surface/kernel/pull/32/commits/437b4979d6ee78cc2c37bfd9d56ff69a9354b277 ("Fixup: BACKPORT: ipts: add static_assert definition to header files")
  (Backporting upstream commits vs defining macros in header files, see commit message for details)
  I added static_assert definition into header files, is that OK?

<details><summary>commit log with annotation</summary>
<p>

#### feature/ipts-no-modeswitch
cherry-picked without conflicts:
69ea9ac9883b - Dorian Stoll, 2019-12-20 : BACKPORT: ipts: Dont automatically switch sensor modes

#### wifi-suspend-fix
cherry-picked without conflicts:
81a669a29c89 - sebanc, 2019-11-04 : BACKPORT: wireless/mwifiex: Fix S0ix / suspend

`git revert <commit>` according to linux-surface 5.3:
0202aad310f9 - kitakar5525, 2020-01-16 : Revert "wireless/mwifiex: Add quirks for Surface devices"

#### feature/companion-no-feedback
cherry-picked without conflicts:
78ec1766f3c2 - Dorian Stoll, 2019-11-10 : BACKPORT: ipts: Add a generic interface for quirks
83eb67d3fecf - Dorian Stoll, 2019-11-08 : BACKPORT: ipts: Let the companion decide about no_feedback

#### feature/ipts-cleanup
cherry-picked without conflicts:
38c751399ae2 - Dorian Stoll, 2019-11-07 : BACKPORT: ipts: Document output of IPTS debug thread
16d63247c70b - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Remove ipts prefix from driver source files
75345e31de4d - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Move debugging settings into modparams

Fixup by me:
437b4979d6ee - kitakar5525, 2020-01-16 : Fixup: BACKPORT: ipts: add static_assert definition to header files
5928135124b5 - kitakar5525, 2020-01-16 : Fixup: BACKPORT: ipts: Cleanup ipts-i915 to pass checkpatch

Resolved conflicts by me:
7d81703994fc - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup ipts-i915 to pass checkpatch

cherry-picked without conflicts:
8ab16f2c7911 - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup ipts-mei to pass checkpatch
21832a583a56 - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Update Makefile / Kconfig to pass checkpatch
14ca50918a85 - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup ipts-kernel to pass checkpatch
5874171f44d3 - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup ipts-hid to pass checkpatch
47b71b6ce2e5 - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup public headers to pass checkpatch
79d32d1b7bd0 - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup ipts-surface to pass checkpatch
085f2d3e5a05 - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup ipts-msg-handler to pass checkpatch
6c2bcebcae9a - Dorian Stoll, 2019-10-28 : BACKPORT: ipts: Cleanup ipts-companion to pass checkpatch
36bb00d459e7 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Cleanup ipts-gfx to pass checkpatch
76642e3c6b13 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Cleanup ipts-state.h to pass checkpatch
7672bb090571 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Cleanup ipts-resource to pass checkpatch
83619a6909b1 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Cleanup ipts-params to pass checkpatch
525aeb733530 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Cleanup ipts-dbgfs.c to pass checkpatch
97256f6113e4 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Cleanup ipts-sensor-regs.h to pass checkpatch
b5cd975fc335 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Clean up ipts.h to pass checkpatch
7dfd1b63af47 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Clean up ipts-mei-msg.h to pass checkpatch

#### feature/no-ipts-config-file
cherry-picked without conflicts:
e54ba9e78b54 - Dorian Stoll, 2019-10-27 : BACKPORT: ipts: Address comments by qzed and grayhatter
8700a7f11ed5 - Dorian Stoll, 2019-10-20 : BACKPORT: ipts: Move ipts_fw_config.bin into the companion
c48c2eede077 - Dorian Stoll, 2019-10-20 : BACKPORT: ipts: Implement new companion interface

#### bugfix/touch-rotation
cherry-picked without conflicts:
7e520ac84a52 - Dorian Stoll, 2019-09-18 : BACKPORT: Remove IPTS sensor mode APIs

`git am <patch>` (see commit message for patch location):
2f2ae1a04004 - kitakar5525, 2019-09-06 : BACKPORT: ipts: hid-multitouch: revert all the changes

#### old-patches-cleanup
cherry-picked without conflicts:
cb1113076574 - Maximilian Luz, 2019-09-18 : BACKPORT: Revert downstream_hpd_needs_d0 changes in i915

`git revert <commit>` according to linux-surface 5.3:
1e27f5e319b5 - kitakar5525, 2020-01-16 : Revert "wireless: Add mwlwifi driver"
e1adbeef77f1 - kitakar5525, 2020-01-16 : Revert "power/suspend: Add delay for device quirks"
f346b5b62be1 - kitakar5525, 2020-01-16 : Revert "staging: Add WIP camera drivers for Surfae devices"
5ab0b86c78ae - kitakar5525, 2020-01-16 : Revert "USB: Modify lpm check for sdcard-reader"

</p>
</details>

### CODE REVIEW

**Comment by kitakar5525** [comment]
Oops, I should have separated the following revert commits:
e8e9087 - kitakar5525, 2020-01-16 : Revert "HID: Improve Windows Precision Touchpad detection."
6515d8e - kitakar5525, 2020-01-16 : Revert "sparc64: implement ioremap_uc"

Those commits are not backporting, but needed to be reverted to avoid conflicts between those commits and upstream commits.

I'll separate those two commits.

**Comment by kitakar5525** [comment]
Separating done by making another PR.

**Comment by qzed** [comment]
Looks good to me! Regarding `static_assert`: I think you've chosen the best option.

**Comment by kitakar5525** [comment]
- Oh, I used exact the same commit title from 5.3: "BACKPORT: Revert downstream_hpd_needs_d0 changes in i915_legacy". Is that confusing? Should remove "_legacy"?

- The commit title "Fixup: BACKPORT: add static_assert definition to header files" too generic?
Should be something like "Fixup: BACKPORT: ipts: add static_assert definition to header files"?

**Comment by qzed** [comment]
> * Oh, I used exact the same commit title from 5.3: "BACKPORT: Revert downstream_hpd_needs_d0 changes in i915_legacy". Is that confusing? Should remove "_legacy"?

Yeah, I think dropping the `_legacy` is a good idea.

> * The commit title "Fixup: BACKPORT: add static_assert definition to header files" too generic?
>       Should be something like "Fixup: BACKPORT: ipts: add static_assert definition to header files"?

The `ipts` is a bit clearer, but I'm fine with both.

**Comment by kitakar5525** [comment]
> Yeah, I think dropping the _legacy is a good idea.

> The ipts is a bit clearer, but I'm fine with both.

OK, both done.

**Comment by kitakar5525** [comment]
By the way, when checking generated IPTS patch, checkpatch added one error and one warning compared to IPTS patch for 5.3:
```bash
ERROR: else should follow close brace '}'
#386: FILE: drivers/gpu/drm/i915/intel_guc_submission.c:117:
+	}
+	else {
```
```bash
WARNING: line over 80 characters
#707: FILE: drivers/gpu/drm/i915/intel_ipts.c:204:
+	ret = execlists_context_deferred_alloc(ipts_ctx, dev_priv->engine[RCS], ce);
```

- cause of the error is due to changes after 4.19 and the change was not backported.
On 5.3, the error was already fixed when adding IPTS support (https://github.com/linux-surface/kernel/commit/871f0898981ae340e4c59821f3af9a848f177ea4)

- cause of the warning is due to `execlists_context_deferred_alloc` function definition changes between 4.19 and 5.3, but long-line warning can be ignored for now (and already ignoring some long-lines).

I'll make another PR to fix the error after this PR has been merged.

**Comment by qzed** [comment]
Yeah, I think we can ignore the "line over 80 characters" warnings for now.

@archseer @StollD any last comments?

**Comment by StollD** [comment]
As long as the code works I am fine with it. I wouldn't bother too much with checkpatch and IPTS at this point. If everything goes well, that driver won't be the way forward anyways.

**Comment by qzed** [comment]
Right. I'll test it later and merge it if I don' find any issues.

**Comment by qzed** [comment]
Tested with 4.19.95. Haven't noticed any apparent issues. @kitakar5525 Thank you for your work!

**Pull request merged**
