### PR TITLE
(rework) mwifiex: pcie: skip cancel_work_sync() on reset failure path

### PR DESCRIPTION
**Pull request by kitakar5525**
Hi, this PR is a successor of the previous PR (https://github.com/linux-surface/kernel/pull/57).

This PR
1. reverts previous patch
2. adds updated patch which addressed issues with the previous PR.

The new patch addressed the following:
- Placed `pci_reset_ongoing` variable into `pcie_service_card` (`card->pci_reset_ongoing`) instead of `mwifiex_adapter` (`adapter->pci_reset_ongoing`) (https://github.com/linux-surface/kernel/pull/57#discussion_r495454923)
- Added commit message for why the deadlock happens when reset failed (https://github.com/linux-surface/kernel/pull/57#issuecomment-699493455)

### CODE REVIEW

**Comment by kitakar5525** [comment]
From previous PR (https://github.com/linux-surface/kernel/pull/57#issuecomment-699518964)

> > Also, can I add your above comment to commit message?
> 
> Sure. Btw. you can also add comments to a patch that will not be part of the commit message to the patch by separating the commit message and comment with `---` (the comment then goes between commit message and diff-stat), if you feel that you'd rather include this as comment.

I thought adding the reason why the issue happens into commit message is better.

> > If OK, how can I credit you? (`Co-developed-by`? or just mentioning you in the commit message?)
> 
> Not sure that's really necessary. You developed the patch, so `Co-developed-by` is probably the wrong tag. I just tried to figure out the sequence of why it's going wrong and why this is needed. If you still want to add me, I think the cleanest way is to just mention my first name in the message (or comment) and add my full reference via a `Cc:` tag.

Thanks, I'll `Cc:` you when sending upstream.

**Comment by kitakar5525** [comment]
I'm not sure skipping `cancel_work_sync()` even when reset failed is acceptable or not. I understand `cancel_work_sync()` is there for some reasons. Upstream devs may know anyway.

**Comment by qzed** [comment]
I think it should be fine with reset failure _if_ the device is still being (more or less) usable afterwards and cleanly shut down with a call to `cancel_work_sync()` later (which I kind of assumed). I'd have to take another look at that to see if that's the case. But yeah, ideally we'd move the call to `cancel_work_sync()` to some other place that gives us the necessary guarantees. Problem is I have no clue where, and also what specifically we'd have to guarantee.

**Review by qzed — APPROVED** [review]
Thanks! Feel free to merge if you think it's ready.

**Comment by kitakar5525** [comment]
Thanks! since there are no functional changes from the previous PR, I'll merge this PR with the other open PRs later.

**Comment by kitakar5525** [comment]
Corrected wording in commit message in this rebase.

**Pull request merged**
