### PR TITLE
Ov8865 v1

### PR DESCRIPTION
**Pull request by djrscally**
Hello

This series should add support for the OV8865 front camera to all but the Surface Go and Go2 models. Broadly speaking, everything camera wise seems to work. The picture quality is a bit rubbish because no VCM (the focuser) control...which means it can be a bit blurry. I'm a bit unclear how that links to the sensor driver, but all of this work will be required regardless so thought I may as well link it now.

### CODE REVIEW

**Comment by qzed** [comment]
Thanks! I'll try to find some time to give it a spin in the next couple of days, hopefully tomorrow or so.

**Comment by qzed** [comment]
Okay, that didn't work. Here's the log from `qcam` (the lines separated by space appear when I try to change the camera):

```
[0:00:57.715301966] [2128] ERROR Controls controls.cpp:765 Control 0x00000000 type and info type mismatch
[0:00:57.715404114] [2128] ERROR Controls controls.cpp:765 Control 0x00000000 type and info type mismatch
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[0:00:57.735251920] [2128]  INFO Camera camera_manager.cpp:294 libcamera v0.0.0+2771-e8a28b4b
[0:00:57.744758860] [2130]  WARN CameraSensorProperties camera_sensor_properties.cpp:109 No static properties available for 'ov8865'
[0:00:57.744779276] [2130]  WARN CameraSensorProperties camera_sensor_properties.cpp:111 Please consider updating the camera sensor properties database
[0:00:57.752054617] [2130] ERROR IPU3 ipu3.cpp:1214 Failed to initialise the IPU3 IPA
[0:00:57.759918027] [2130]  INFO IPU3 ipu3.cpp:1192 Registered Camera[0] "\_SB_.PCI0.I2C2.CAMF" connected to CSI-2 receiver 1
[0:00:57.956497852] [2128]  INFO Camera camera.cpp:906 configuring streams: (0) 1280x720-NV12
Using software format conversion from NV12

[0:01:14.912733112] [2128] ERROR Camera camera.cpp:410 Camera in Running state trying acquire() requiring state Available
Failed to acquire camera \_SB_.PCI0.I2C2.CAMF
[0:01:16.157859068] [2128] ERROR Camera camera.cpp:410 Camera in Running state trying acquire() requiring state Available
Failed to acquire camera \_SB_.PCI0.I2C2.CAMF
[0:01:20.739614195] [2128] ERROR Camera camera.cpp:410 Camera in Running state trying acquire() requiring state Available
Failed to acquire camera \_SB_.PCI0.I2C2.CAMF
```

Here's a dmesg log: [dmesg.log](https://github.com/linux-surface/kernel/files/6834830/dmesg.log). Libcamera is at `e8a28b4b`.

**Comment by djrscally** [comment]
@qzed ok - thanks for testing. Remind me what machine you have, please?

**Comment by qzed** [comment]
Oh right, sorry. Tested this on a Surface Book 2.

**Comment by djrscally** [comment]
@qzed OK; damn, nothing there looks obviously wrong then...\_SB_.PCI0.I2C2.CAMF is the ov5693, I guess qcam is trying to restart it after failing to run the ov8865 and just not doing it quite right. ov8865 must have probed properly or it wouldn't even be an option in qcam (and in fact nor would ov5693 thanks to the ipu3-cio2 driver not finalising everything till all connected sensors probe)...that points, I think, to some silent problem with the power up sequence...do you get a blip of privacy LED when you attempt to start qcam?

**Comment by qzed** [comment]
> ov8865 must have probed properly or it wouldn't even be an option in qcam

The ov8865 isn't an option (there's only the ov5693). The error comes when I select that. I've also checked that with the current v5.12 kernel and the error also shows there, so we can probably ignore that for now.

> do you get a blip of privacy LED when you attempt to start qcam?

No, I don't. There's also none at boot, unlike the ov5693 one.

**Comment by djrscally** [comment]
Oh! Gotcha. Then almost certainly it's silently failing probe. Can you
check /sys/bus/i2c/devices/i2c-INT347A:00 for a driver directory to
confirm?

**Comment by qzed** [comment]
Seems like a driver is bound:

```
$ ll /sys/bus/i2c/devices/i2c-INT347A:00/
Permissions  Size User Date Modified Name
lrwxrwxrwx      0 root 18 Jul 01:45  driver -> ../../../../../../bus/i2c/drivers/ov8865
lrwxrwxrwx      0 root 18 Jul 01:46  firmware_node -> ../../../../../LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:76/INT347A:00
drwxr-xr-x      - root 18 Jul 01:47  power
lrwxrwxrwx      0 root 18 Jul 01:45  subsystem -> ../../../../../../bus/i2c
lrwxrwxrwx      0 root 18 Jul 01:46  supplier:regulator:regulator.0 -> ../../../../../virtual/devlink/regulator:regulator.0--i2c:i2c-INT347A:00
drwxr-xr-x      - root 18 Jul 01:47  video4linux
.r--r--r--  4.0Ki root 18 Jul 01:47  modalias
.r--r--r--  4.0Ki root 18 Jul 01:47  name
.rw-r--r--  4.0Ki root 18 Jul 01:47  uevent
```

**Comment by djrscally** [comment]
@qzed

I forgot that libcamera needed a patch too, though the error message doesn't exactly match what it was when I did this...can you try:

```patch
commit 3131ac95502f2ca719ba142c052d1aae8cfd4ea6 (HEAD -> master)
Author: Daniel Scally <djrscally@gmail.com>
Date:   Sun Jul 18 14:53:58 2021 +0100

    Add ov8865 specific information
    
    Add sensor specific information to camera_sensor_helper.cpp for the ov8865
    
    Signed-off-by: Daniel Scally <djrscally@gmail.com>

diff --git a/src/ipa/libipa/camera_sensor_helper.cpp b/src/ipa/libipa/camera_sensor_helper.cpp
index 709835a8..e72167ec 100644
--- a/src/ipa/libipa/camera_sensor_helper.cpp
+++ b/src/ipa/libipa/camera_sensor_helper.cpp
@@ -325,6 +325,16 @@ public:
 };
 REGISTER_CAMERA_SENSOR_HELPER("ov13858", CameraSensorHelperOv13858)
 
+class CameraSensorHelperOv8865 : public CameraSensorHelper
+{
+public:
+       CameraSensorHelperOv8865()
+       {
+               analogueGainConstants_ = { AnalogueGainLinear, 1, 0, 0, 128 };
+       }
+};
+REGISTER_CAMERA_SENSOR_HELPER("ov8865", CameraSensorHelperOv8865)
+
 #endif /* __DOXYGEN__ */
 
 } /* namespace ipa */
diff --git a/src/libcamera/camera_sensor_properties.cpp b/src/libcamera/camera_sensor_properties.cpp
index 7d8ba9e9..8cd22bfa 100644
--- a/src/libcamera/camera_sensor_properties.cpp
+++ b/src/libcamera/camera_sensor_properties.cpp
@@ -102,6 +102,20 @@ const CameraSensorProperties *CameraSensorProperties::get(const std::string &sen
                                 */
                        },
                } },
+               { "ov8865", {
+                       .unitCellSize = { 1400, 1400 },
+                       .testPatternModes = {
+                               { 0, controls::draft::TestPatternModeOff },
+                               { 2, controls::draft::TestPatternModeColorBars },
+                               /*
+                                * No corresponding test pattern mode for:
+                                * 1: "Random data"
+                                * 3: "Colour Bars with Rolling Bar"
+                                * 4: "Color squares"
+                                * 5: "Color squares with rolling bar"
+                                */
+                       }
+               } },
        };
 
        const auto it = sensorProps.find(sensor);
```

...need to upstream these to libcamera too

**Comment by qzed** [comment]
Awesome, thanks! Applying that patch does the trick! The camera is flipped horizontally though (I'll have to check if windows does that as well or how that handles front vs back camera flipping).

One thing that I've noticed is that there's a hick-up when I switch cameras in qcam on the fly for the first time, emitting
```
[0:11:25.452246189] [4728]  INFO Camera camera.cpp:720 Pipeline handler in use by another process
Failed to acquire camera \_SB_.PCI0.I2C2.CAMF
```

Trying that again works and produces
```
Switching to camera \_SB_.PCI0.I2C2.CAMF
[0:11:32.453796900] [4728]  INFO Camera camera.cpp:906 configuring streams: (0) 1280x720-NV12
Using software format conversion from NV12
```

**Comment by qzed** [comment]
> I'll have to check if windows does that as well or how that handles front vs back camera flipping

Did that: The user-facing camera is the same way around both on Linux and Windows whereas the world-facing one is flipped horizontally on Linux. Either we're missing that logic/properties or Windows does some handling for automatically flipping world-facing cameras or something like that.

**Comment by djrscally** [comment]
Fantastic, glad it's working! I have the horizontal flip too...not got
round to diagnosing. In theory Fabwu's rotation patch should fix it because
then libcamera will flip it, but it should be in this kernel already right?

I'm gonna focus on libcamera for a few weeks soon...most of the auto focus
work will be there, I'll see if I can fix those errors too.

**Comment by qzed** [comment]
> I have the horizontal flip too...not got round to diagnosing. In theory Fabwu's rotation patch should fix it because then libcamera will flip it, but it should be in this kernel already right?

I thought so too (there's at least ce2ea6d95459c1805d593a45d078b05f04a71bd3). That's why I'm wondering if there's supposed to be some logic considering the placement of the camera, i.e. different property interpretation depending on whether it's a front or back camera or something. Just guessing though, might also be something that I'm missing.

> I'm gonna focus on libcamera for a few weeks soon...most of the auto focus work will be there, I'll see if I can fix those errors too.

Top, thanks again! I'll review this series in a bit, looks good so far!

**Review by qzed — APPROVED** [review]
Thanks! Looks good as far as I can tell.

**Pull request merged**
